services:
  face-service:
    container_name: otr-face-service
    build:
      context: ./face-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  stt-service:
    container_name: otr-stt-service
    build:
      context: ./stt-service
    ports:
      - "8020:8020"
    env_file:
      - .env
    restart: unless-stopped
